= Elasticsearch

To add a new field to the mapping see DINA https://aafc-bicoe.github.io/dina-local-deployment/#_how_to_update_elasticsearch_mapping[deployment documentation].

== Update Mapping

When a new mapping or new mapping property must be added to a live index the
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html[Update mapping API] can be used.

If the new mapping requires new Analyzer, an https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html[update settings analysis] is required first.

Example:

Assuming `keyword_lowercase_analyzer` is already declared, add it to the multi-field `data.attributes.originalFilename`:
----
curl -X PUT "localhost:9200/dina_object_store_index/_mapping?pretty" -H 'Content-Type: application/json' -d'
{
  "properties": {
    "data.attributes.originalFilename": {
      "type": "text",
      "fields": {
        "prefix": {
          "type": "text",
          "analyzer": "keyword_lowercase_analyzer",
          "index_prefixes": {
            "min_chars" : 1,
            "max_chars" : 10
          }
        },
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      }
    }
  }
}
'
----

Refesh the index:

----
curl -X POST "localhost:9200/dina_object_store_index/_update_by_query?refresh"
----

== Delete Included Field with Update By Query

To remove a specific field from a nested object within your Elasticsearch documents, you can use an `update_by_query` request:

*POST 127.0.0.1:9200/dina_material_sample_index/_update_by_query*
----
{
  "script": "for (int i = 0; i < ctx._source.included.length; ++i) { ctx._source.included[i].attributes.remove(\"ATTRIBUTE_NAME\") }",
  "query": {
    "nested": {
      "path": "included",
      "query": {
        "bool": {
          "must": [
            {
              "exists": {
                "field": "included.attributes.ATTRIBUTE_NAME"
              }
            }
          ]
        }
      }
    }
  }
}
----

Replace `ATTRIBUTE_NAME` with the field you wish to remove. And also change the index in the URL if needed. Then you can re-run the elastic-configurator.

In the elastic-configurator, you should see the following for the index you have updated if it worked correctly:

----
Running update script for optional mapping
The update request was successful
Re-indexing documents.
Source index is: dina_material_sample_index_20241112154013 and destination index is: dina_material_sample_index_20241112193452
Response is: 200
Old index doc count: 2 
New index doc count: 2
Document counts match. Proceeding with deletion of old index and setting alias...
Updating index dina_material_sample_index_20241112193452 with alias dina_material_sample_index
----

Then, re-index the affected documents so the data is restored in the new format based on the migration.
