= Liquibase

http://www.liquibase.org/index.html[Liquibase] is used to generate the database and migrate to new versions of the database schema. Changelogs are source xml files that describe schema changes to the database. Liquibase maintains a "DATABASECHANGELOG" table in the same database to keep track of which changelogs have been executed. When the application starts, any changelogs that have not been executed are executed.

Additional information:

* http://www.liquibase.org/bestpractices.html[Liquibase Best Practices]
* https://www.liquibase.org/documentation/changes/add_column.html[Change example: addColumn]
* https://www.liquibase.org/documentation/generating_changelogs.html[Adding Liquibase support to an existing database]

== Liquibase Contexts

When developing for Dina modules certain data is needed for the application to run properly and to make testing easier. Which is why we separate our database migrations into categories known as contexts. The two main contexts are as follows:

* schema-change
** Changes to the schema such as adding new columns, renaming tables, adding new tables.
* sample-data
** sample data for developers, this should not be ran on PROD/UAT since it's used for inserting sample data for developers and the data is already in PROD/UAT databases.

For PROD/UAT purposes, the context can be changed by editing the application.yml file which has all of the liquibase configurations. The contexts are a comma separated list of all of the contexts to be performed.

== Liquibase migration file convention

The following convention should be followed by all Liquibase database migration files:

* Migration scripts live in `src/main/resources/db/changelog`
* Filename should follow the convention `<UNIQUE_INCREMENTAL_ID>-<ISSUE_TITLE>.xml` (e.g. `2-new_specimen_field_PHAC_containment_level.xml`)
* A new migration file's path should be added in an "include" tag of `src/main/resources/db/changelog/db.changelog-master.xml`
* The context of a `changeSet` in the migration xml file should always be set (e.g. `context="schema-change"`)
* The `<id>` should use the filename convention without the file extension `<UNIQUE_INCREMENTAL_ID>-<ISSUE_TITLE>` if the file only includes 1 changeset, otherwise the following convention should be used: `<UNIQUE_INCREMENTAL_ID>-<ISSUE_TITLE>-<WHAT_THE_CHANGESET_DOES>` (ex: `id="11-Implement_new_workflow_entitie-Create_enum_types"`)

When merging code to dev, we need to make sure the incremental number is always unique. If we have a duplicate, we should be reassigned a new identifier and update the `db.changelog-master.xml`.

== Run Liquibase from Maven

It may be useful to run Liquibase without running the application. The Liquibase website has an https://docs.liquibase.com/tools-integrations/maven/workflows/creating-liquibase-projects-with-maven-postgresql.html[example] and https://github.com/AAFC-BICoE/seqdb-api[seqdb-api] contains the plugin defition and an example `liquibase.properties` file.
