= Releasing a dina module

The process of releasing a dina module is the same for all modules. The CI will automaticaly build and release a new Docker image to Docker Hub when something is merged
in the master/main branch.

BICoE Docker Hub: https://hub.docker.com/u/aafcbicoe

Java-based API:

. From dev branch
.. Change the version by running `mvn versions:set -DnewVersion=X.X` from the root where `X.X` is the current version minus the `-SNAPSHOT`
.. Add and Push to dev with message like "Prepare version x.x release"
.. Wait for CI to complete
. From master/main
.. Merge dev into master (do NOT use Pull Request)
.. Push to master (it will trigger the deployment Docker Hub)
. Create a new https://github.com/AAFC-BICoE/dina-base-api/releases[GitHub release]
.. Add a Summary of the changes (looks at the previous versions for an example)
.. Publish the Release
. From dev branch
.. Change the version by running `mvn versions:set -DnewVersion=X.X-SNAPSHOT` from the root where X.X is the next increment in the version number
.. Add and Push to dev with message like "Prepare next development version"
