[[collection-component]]
= Collection Component

[[collection]]
== Collection

A Collection represents the top entity that can contain material-sample. Top collections (or parent collections) generally represent a natural history collection or a laboratory. A collection can contain multiple sub-collection(s).

[[collecting-event]]
== Collecting Event

Darwin Core defines "event" as : An action that occurs at some location during some time. (from https://dwc.tdwg.org/terms/#event[DarwinCore]).
In a Collection Event, the action is the extration from nature.

[[mat-sample]]
== Material Sample
A physical result of a sampling event.

In natural history collections, the material sample is typically collected, and either preserved or destructively processed. (from https://dwc.tdwg.org/terms/#materialsample[DarwinCore]).

[[organism]]
== Organism
A particular organism or defined group of organisms considered to be taxonomically homogeneous. (from https://dwc.tdwg.org/terms/#organism[DarwinCore]).

[[project]]
== Project

[[collection-method]]
== Collection Method

Methods used during an Collecting Event. Examples: UV light trap, bottom traw

Similar to DarwinCore https://dwc.tdwg.org/terms/#dwc:samplingProtocol[samplingProtocol].

[[preparation-type]]
== Preparation Type

A noun representing the state of a material sample. Examples: sheet, liquid nitrogen
