[[collection-component]]
= Collection Component

[[assemblage]]
== Assemblage

Mechanism used to group material samples according to a generic, administrative theme. Should not be confused with <<project>>. Examples might include specimen books or exsiccatae in herbaria where there is a title and a description and possibly enhanced with <<managed_attributes>> for additional metadata that depicts the group's identity.

[[association]]
== Association

=== Host Organism
Organism that is the host of the material-sample. Usualy mean that we have the host (collected/cultivated). Not to be confused with <<ce-host>> of the collecting-event where the host was observed but not collected.

[[collection]]
== Collection

A Collection represents the top entity that can contain material-sample. Top collections (or parent collections) generally represent a natural history collection or a laboratory. A collection can contain multiple sub-collection(s).

[[collecting-event]]
== Collecting Event

Darwin Core defines "event" as : An action that occurs at some location during some time. (from https://dwc.tdwg.org/terms/#event[DarwinCore]).
In a Collection Event, the action is the extraction from nature.

=== Collection Number

An identifier given to the event in the field at the time of collecting one or more samples. Often serves as a link between field notes and the Event.

Same as DarwinCore https://dwc.tdwg.org/terms/#dwc:fieldNumber[fieldNumber]

=== Collector's Number

An identifier given to the Occurrence, by the collector, at the time it was recorded. Often serves as a link between field notes and an Occurrence record, such as a specimen collector's number.

Same as DarwinCore https://dwc.tdwg.org/terms/#dwc:recordNumber[recordNumber]

[[collection-method]]
=== Collection Method

Method used during an Collecting Event. Examples: UV light trap, bottom traw

Similar to DarwinCore https://dwc.tdwg.org/terms/#dwc:samplingProtocol[samplingProtocol].

=== Coordinate Uncertainty In Meters

The horizontal distance in meters from the given decimalLatitude and decimalLongitude describing the smallest circle containing the whole of the Location.
(from https://dwc.tdwg.org/terms/#dwc:coordinateUncertaintyInMeters[Darwin Core])

=== Habitat

An environmental system which can sustain and allow the growth of an ecological population. (from https://ontobee.org/ontology/ENVO?iri=http://purl.obolibrary.org/obo/ENVO_01000739[Ontobee])

[[ce-host]]
=== Host

Observed host of the material-sample at the time of the collecting-event.

=== Substrate

Observed surface on which an organism was collected and understood to have lived.

(based on http://www.wikidata.org/entity/Q5824490)

== Determination
Determinations are attached to an <<organism>>. There is always a primary determination defined. Determination history is preserved.

== Effective Determination(s)
The effective determination refers to the first primary determination that can be found in the material-sample lineage. If a target <<organism>> is defined, the effective determination will be restricted to it otherwise all the organism will be grouped to return the effective determinations.

[[mat-sample]]
== Material Sample
A physical result of a sampling event.

In natural history collections, the material sample is typically collected, and either preserved or destructively processed. (from https://dwc.tdwg.org/terms/#materialsample[DarwinCore]).

[[mat-samp-type]]
=== Material Sample Type
A Material Sample is a physical result of a sampling (or subsampling) event. In biological collections, the material sample is typically collected, and either preserved or destructively processed. A Material Sample Type is a system-defined term that prescribes the downstream expectations and logic in how derivative (or child) Material Samples are to be interpreted and digitally managed.
Fixed values include: `Whole Organism`, `Culture Strain`, `Molecular Sample`, `Organism Part` or `Mixed Organisms`.

[[mat-samp-state]]
=== Material Sample State
Represents the state of a material sample when its condition is negatively impacted. Fixed values include: destroyed, damaged, lost or decommissioned

[[preparation]]
== Preparation

Preparation can either be for preservation or propagation purpose.

[[preparation-type]]
=== Preparation Type

A noun representing what is getting prepared.

(inspired by https://abcd.tdwg.org/terms/#preparationType[ABCD 3.0])

Examples: `leg`, `tissues`, `DNA`

[[preparation-method]]
=== Preparation Method

A noun representing the process used (the how) in preparing the material sample.

(inspired by https://abcd.tdwg.org/[ABCD 3.0])

Examples: `culture`, `mechanical inoculation`, `dissection`

[[preservation-type]]
=== Preservation Type
Description of the preservation type of the material sample.

Examples: `Freeze-Dry`
(from https://abcd.tdwg.org/terms/#preservationType[ABCD 3.0])

[[preparation-fixative]]
=== Preparation Fixative
Solution that was applied to or in which the material sample is preserved.
Examples: `EtOH 95%`, `EtOH 75%`, `EtOH 70%`, `saline`, `glue`

[[preparation-materials]]
=== Preparation Materials
Additional, typically inert physical environments or objects in which or on which the organism in a material sample is stored. It does not express the state of the organism nor the fixatives used but rather the materials that allow the organism to be presented.

Examples: `pinned`, `glass vial`, `plastic jar`, `glass jar`, `microscope slide`, `acid-free paper`, `sticky trap/card`, `Eppendorf tube`

[[preparation-substrate]]
=== Preparation Substrate
Material on which the organism in the material sample is presented or grows.
Examples: rock, log, agar

[[organism]]
== Organism
A particular organism or defined group of organisms considered to be taxonomically homogeneous. (from https://dwc.tdwg.org/terms/#organism[DarwinCore]).
Optionally, it is possible to define a target organism within a material sample.

[[project]]
== Project
Project has a start and an end date. It usually links to the organizational definition of project where an objective, a scope, resources and deliverable are defined.
A material sample can be linked to multiple projects.

== Protocol

Predefined written procedural method in the design and implementation of experiments in natural sciences.
(from http://www.wikidata.org/entity/Q367158[Wikidata])

[[split]]
== Split
The concept of a split represents the action of creating new material sample(s) from an existing material sample. The provenance of the new material sample(s) is preserved. For example, the action can be a dissection or fungal/bacterial propagation.

Split can be configured using a form template with a <<split-configuration>> setup.

Limitation: The result of a split (called children) cannot have their own collecting event. Since the extraction from nature happened on the first material sample, children will inherit the one from the first parent.

[[direct-parent-strategy]]
=== Direct Parent Naming Strategy

Using that strategy, the generated children will get the next name available among the list of children of the direct parent.

----
ABC-01
|_ ABC-01-A
  |_ ABC-01-A-a
  |_ ABC-01-A-b
|_ ABC-01-B
  |_ ABC-01-B-a
----

Based on the structure above:
[options="header"]
.Direct Parent Strategy examples
|==========================
| Split From  | Result  
| ABC-01      | ABC-01-C
| ABC-01-A    | ABC-01-A-c
| ABC-01-B    | ABC-01-B-b
|==========================

[[material-sample-type-strategy]]
=== Material Sample Type Naming Strategy

Using that strategy, the generated children will get the next name available among the complete set of material sample of the same <<mat-samp-type>> in the entire lineage.

----
ABC-01 (Whole Organism)
|_ ABC-01-A (Culture Strain)
  |_ ABC-01-B
  |_ ABC-01-E
|_ ABC-01-C
  |_ ABC-01-D
----

Based on the structure above:
[options="header"]
.Type Based Strategy examples
|==========================
| Split From  | Type Created    |Result  
| ABC-01      | Culture Strain   | ABC-01-F
| ABC-01-A    | Culture Strain   | ABC-01-F
| ABC-01-B    | Molecular Extract| ABC-01-B-a
|==========================

[[restrictions]]
== Restrictions

Restriction levels are regulations set by the Public Health Agency of Canada (PHAC) and the Canadian Food Inspection Agency (CFIA). Levels set, or restrictions remarks made will tag the material sample with the appropriate level or note. The “Restricted” button toggle is decoupled from the tags.

Risk groups(RG) are classifications defined by the PHAC based on a biologic’s inherent characteristics and its prevalence for pathogenicity, virulence, risk of spread and availability of effective treatment. The risk group directs the appropriate containment level required to safely handle the specimen and dictates standard operating procedures.

Notes made in the `Restrictions Remarks` section will have its own red alert box when viewing the material sample. Note that only a single box will be created for the restrictions remarks; a new line does not create a new box.

[[scheduled_actions]]
== Scheduled Actions

Only for reporting and record keeping purposes. No alerts will be triggered automatically on assigned date. Multiple actions can exist.
