[[collection-component]]
= Collection Component

[[collection]]
== Collection

A Collection represents the top entity that can contain material-sample. Top collections (or parent collections) generally represent a natural history collection or a laboratory. A collection can contain multiple sub-collection(s).

[[collecting-event]]
== Collecting Event

Darwin Core defines "event" as : An action that occurs at some location during some time. (from https://dwc.tdwg.org/terms/#event[DarwinCore]).
In a Collection Event, the action is the extraction from nature.

[[collection_numbers]]
=== Collection Number

An identifier given to the event in the field. Often serves as a link between field notes and the Event.
Same as DarwinCore https://dwc.tdwg.org/terms/#dwc:fieldNumber[fieldNumber]

=== Collector's Number

An identifier given to the Occurrence at the time it was recorded. Often serves as a link between field notes and an Occurrence record, such as a specimen collector's number.

Same as DarwinCore https://dwc.tdwg.org/terms/#dwc:recordNumber[recordNumber]


[[collection-method]]
=== Collection Method

Method used during an Collecting Event. Examples: UV light trap, bottom traw

Similar to DarwinCore https://dwc.tdwg.org/terms/#dwc:samplingProtocol[samplingProtocol].

=== Coordinate Uncertainty In Meters

The horizontal distance in meters from the given decimalLatitude and decimalLongitude describing the smallest circle containing the whole of the Location.
(from https://dwc.tdwg.org/terms/#dwc:coordinateUncertaintyInMeters[Darwin Core])

=== Host

Observed host of the material-sample at the time of the collecting-event.

=== Substrate

Observed surface on which an organism was collected and understood to have lived.

(based on http://www.wikidata.org/entity/Q5824490)

[[mat-sample]]
== Material Sample
A physical result of a sampling event.

In natural history collections, the material sample is typically collected, and either preserved or destructively processed. (from https://dwc.tdwg.org/terms/#materialsample[DarwinCore]).

[[mat-samp-type]]
=== Material Sample Type
A Material Sample is a physical result of a sampling (or subsampling) event. In biological collections, the material sample is typically collected, and either preserved or destructively processed. A Material Sample Type is a system-defined term that prescribes the downstream expectations and logic in how derivative (or child) Material Samples are to be interpreted and digitally managed.
Fixed values include: `Whole Organism`, `Molecular Sample`, `Organism Part` or `Mixed Organisms`.

[[mat-samp-state]]
=== Material Sample State
Represents the state of a material sample when its condition is negatively impacted. Fixed values include: destroyed, damaged, lost or decommissioned

[[preparation]]
== Preparation

Preparation can either be for preservation or propagation purpose.

[[preparation-type]]
=== Preparation Type

A noun representing what is getting prepared.

(inspired by https://abcd.tdwg.org/terms/#preparationType[ABCD 3.0])

Examples: `leg`, `tissues`, `DNA`

[[preparation-method]]
=== Preparation Method

A noun representing the process used (the how) in preparing the material sample.

(inspired by https://abcd.tdwg.org/[ABCD 3.0])

Examples: `culture`, `mechanical innoculation`, `dissection`

[[preservation-type]]
=== Preservation Type
Description of the preservation type of the material sample.

Examples: `Freeze-Dry`
(from https://abcd.tdwg.org/terms/#preservationType[ABCD 3.0])

[[preparation-fixative]]
=== Preparation Fixative
Solution that was applied to or in which the material sample is preserved.
Examples: `EtOH 95%`, `EtOH 75%`, `EtOH 70%`, `saline`, `glue`

[[preparation-materials]]
=== Preparation Materials
Additional, typically inert physical environments or objects in which or on which the organism in a material sample is stored. It does not express the state of the organism nor the fixatives used but rather the materials that allow the organism to be presented.

Examples: `pinned`, `glass vial`, `plastic jar`, `glass jar`, `microscope slide`, `acid-free paper`, `sticky trap/card`, `Eppendorf tube`

[[preparation-substrate]]
=== Preparation Substrate
Material on which the organism in the material sample is presented or grows.
Examples: rock, log, agar

[[organism]]
== Organism
A particular organism or defined group of organisms considered to be taxonomically homogeneous. (from https://dwc.tdwg.org/terms/#organism[DarwinCore]).

[[project]]
== Project

== Protocol

Predefined written procedural method in the design and implementation of experiments in natural sciences.
(from http://www.wikidata.org/entity/Q367158[Wikidata])

[[split]]
== Split
In DINA, the concept of a split represents the action of creating new material sample(s) from an existing material sample. The provenance of the new material sample(s) is preserved. For example, the action can be a dissection or fungal/bacterial propagation.

Limitation: The result of a split (called children) cannot have their own collecting event. Since the extraction from nature happened on the first material sample, children will inherit the one from the first parent.
