[[collection-component]]
= Collection Component

[[collection]]
== Collection

A Collection represents the top entity that can contain material-sample. Top collections (or parent collections) generally represent a natural history collection or a laboratory. A collection can contain multiple sub-collection(s).

[[collecting-event]]
== Collecting Event

Darwin Core defines "event" as : An action that occurs at some location during some time. (from https://dwc.tdwg.org/terms/#event[DarwinCore]).
In a Collection Event, the action is the extration from nature.

[[collection_numbers]]
=== Collection Numbers

An identifier given to the event in the field. Often serves as a link between field notes and the Event.

Same as DarwinCore https://dwc.tdwg.org/terms/#dwc:fieldNumber[fieldNumber]

[[collection-method]]
=== Collection Method

Method used during an Collecting Event. Examples: UV light trap, bottom traw

Similar to DarwinCore https://dwc.tdwg.org/terms/#dwc:samplingProtocol[samplingProtocol].

[[mat-sample]]
== Material Sample
A physical result of a sampling event.

In natural history collections, the material sample is typically collected, and either preserved or destructively processed. (from https://dwc.tdwg.org/terms/#materialsample[DarwinCore]).

[[mat-samp-type]]
=== Material Sample Type
A Material Sample is a physical result of a sampling (or subsampling) event. In biological collections, the material sample is typically collected, and either preserved or destructively processed. A Material Sample Type is a system-defined term that prescribes the downstream expectations and logic in how derivative (or child) Material Samples are to be interpreted and digitally managed.
Fixed values include: Whole Organism, Molecular Sample, Organism Part or Mixed Organisms.

[[mat-samp-state]]
=== Material Sample State
Represents the state of a material sample when its condition is negatively impacted. Fixed values include: destroyed, damaged, lost or decommissioned

[[preparation]]
== Preparation

[[preparation-type]]
=== Preparation Type

A noun representing the preparation protocol. Preparation can either be for preservation or multiplication purpose.

Examples: `culture`, `mechanical innoculation`

[[preservation-type]]
=== Preservation Type
Description of the preservation type of the material sample.

Examples: `Freeze-Dry`
(from https://abcd.tdwg.org/terms/#preservationType[ABCD 3.0])

[[preparation-fixative]]
=== Preparation Fixative
Solution that was applied to or in which the material sample is preserved.
Examples: `EtOH 95%`, `EtOH 75%`, `EtOH 70%`, `saline`, `glue`

[[preparation-medium]]
=== Preparation Medium
Additional, typically inert physical environments or objects in which or on which the organism in a material sample is stored. It does not express the state of the organism nor the fixatives used but rather the materials that allow the organism to be presented.

Examples: `pinned`, `glass vial`, `plastic jar`, `glass jar`, `microscope slide`, `acid-free paper`, `sticky trap/card`, `Eppendorf tube`

[[preparation-substrate]]
=== Preparation Substrate
Material on which the organism in the material sample is presented or grows.
Examples: rock, log, agar

[[organism]]
== Organism
A particular organism or defined group of organisms considered to be taxonomically homogeneous. (from https://dwc.tdwg.org/terms/#organism[DarwinCore]).

[[project]]
== Project

