[[general-concepts]]
= General Concepts

[[group]]
== Group

Groups are used to define set of users for administration purpose (mostly permissions). They usually align with collections.
A user can belong to more than 1 group.

Groups are also used to defined who owns an object. For example, an object in the object-store always belongs to a group.
Objects can only have 1 owner.

== Role

With the exception of Administrator, roles are always assigned per group.

.Roles:
Administrator::
    DINA Administrator
Super User::
    Group administrator
User::
    Regular user
Guest::
    Similar to a regular user but with less permissions on destructive operations
Read-Only::
    No data alteration possible

== Permissions

Permissions in DINA are strictly related to roles per the table below:

.Minimum role required for operation
[options="header"]
|=======================
|Resource              |Create      |Update      |Delete
|Material Sample       |Guest       |Guest       |User
|Controlled Vocabulary |Super User  |Super User  |Super User
|Form Template         |Object Owner|Object Owner|Object Owner
|Object Store objects  |Guest       |Guest       |Super User
|Agent (person)        |Guest       |Super User  |Super User
|=======================

Technicals: Permissions are mostly https://en.wikipedia.org/wiki/Role-based_access_control[Role-based access control] combined with https://en.wikipedia.org/wiki/Discretionary_access_control[Discretionary access control] with owner.


[[user]]
== User

Users (when explicitly allowed) can access the system. What a user can and cannot do is based on the group(s)/permission(s). When using an external Identity Provider (e.g. ESAS) the user account must be linked to the Identity Provider account. Once done, the user will be able to use a third-party authentication (e.g. ESAS) to access the system.

[[verbatim]]
== Verbatim

DINA has some fields that are prefixed with the word "verbatim". Verbatim is defined as "in exactly the same words as were used originally". These fields are used to capture the data as originally represented for example on a label or in in expedition notes.

[[identifiers]]
== DINA Identifiers

All object in DINA are identified with UUID (universally unique identifier). While this type of identifier is not considered human-readable (123e4567-e89b-12d3-a456-426614174000) it has the property to be virtually universally unique (chances of duplicates are close enough to zero to be considered negligible). Objects can be uniquely identifed even outside the DINA system.

[[primary_id]]
== Primary ID

Preferably unique identifier set by user. Non-unique identifiers are allowed and will require user to override duplication alert "Allowing Duplicate". This should *only* be done for historical bookkeeping purposes.

[[next_identifier]]
=== Next Available Identifier

Unique Primary ID creation by system for a material by concatenating the associated Collection string with the lowest unused integer. Ticking off the box will block manual <<primary_id>> entry.

[[barcode]]
== Barcode

Machine readable code output that would be obtained from a scanning gun. Can be used as another means of searching the database.

[[form_template]]
== Form Template

Form templates are used to customize the user interface by allowing you to choose field visibility and default values. The user can then use them for data entry on a single page or through a split operation.

=== Visibility
The owner (the user who created the template) can always see/use its templates. Optionally, the template can be made available to an entire <<group>> that the user has access to.

Allowing other users to see a group does not give them access to edit the form template, they are only able to use the form template.

[[split-configuration]]
=== Split Configuration

Split Configurations enable you to configure how Material Sample <<split>>s are automatically named and under what conditions they can be used.

==== Condition Setup

The Condition controls when a split configuration can be used. Currently, the only supported Condition Type is `Material Sample Type` condition but multiple Material Sample Types can be configured.

A condition can be applied that this split configuration can only be used if the Material Sample being split from is a specific Material Sample Type.

==== Material Sample Name Generation

The <<direct-parent-strategy>> and <<material-sample-type-strategy>> are available to use as strategies.

When using the `Material Sample Type` strategy, you will need to define the `Material Sample Type` in the `Material Sample Info` data component.

==== Generation Options

Once you have configured the `Strategy`, you can choose how the sequence should be generated. Using `a (Lowercase letters)` and `A (Uppercase letters)` options will start the sequence at the beginning of the alphabet, before moving on to two-letter sequences starting with "AA", "AB", and so on.

[[field_extensions]]
== Field extensions

Field extensions are fields with specific definitions that are defined by known standards. In order to add a specific field extension, a system administrator needs to provide a configuration file to the application.

[[managed_attributes]]
== Managed Attributes

Managed attributes are attributes that can be created and used by the users on-demand. They are usually used to track data that is not common enough to be captured in a regular field. A managed attribute can be of type `integer`, `string`, `date` or `boolean`.

[[material_sample_attachment]]
== Material Sample Attachments

Attachments refer to <<object-store-component>>.

[[date_search]]
== Date Search

Resources may contain fields of the date type in the format YYYY-MM-DD. These date fields can be used to search for resources with a few different parameters including equals to, before, or after the input date. 

For example, a Material Sample, Sample 1, may have a Created On field with the value 2023-05-16. Searching by Created On with the parameter Equals and an input value 2023-05-16 will correctly filter for Sample 1. However, searching with partial date values such as 2023-05 or 2023 will not correctly filter for Sample 1. Users should approach date searches with the full, correct date format of YYYY-MM-DD.
