= Glossary

[[agent-string]]
== Agent String

In-place, in-context verbatim, character-by-character representations of one or more person and/or one or more organization. Example: "M. et Mme Jacques Brossard" as Verbatim Collector in a Collecting Event.

[[geo-names]]
== Geographic names
Names of any geographical or topographical feature of public or historical interest. A geographical name is a proper noun applied to a natural, man-made or cultural feature on Earth. A feature can have different names in one or several languages and the names may be provided, together with appropriate information on the feature, in different products like maps and gazetteers as well as respective services. Based on defintion from https://inspire.ec.europa.eu/theme/gn[EU INSPIRE].

[[geoferencing]]
== Georeferencing
Georeferencing means to associate an object with a position in physical space. Postion is most commonly represented using a coordinate reference system, which in turn can be related to a geodetic reference system such as WGS-84.

[[person]]
== Person
A definitive, canonical representation of a human in the Agent module that has been ideally disambiguated through inclusion of an externally referenced identifier.

[[reverse-geocoding]]
== Reverse geocoding
Reverse geocoding is the process of converting a location as described by geographic coordinates (latitude, longitude) to a human-readable place name.

