= Glossary

[[agent-string]]
== Agent String

In-place, in-context verbatim, character-by-character representations of one or more person and/or one or more organization. Example: "M. et Mme Jacques Brossard" as Verbatim Collector in a Collecting Event.

[[geo-names]]
== Geographic names
Names of any geographical or topographical feature of public or historical interest. A geographical name is a proper noun applied to a natural, man-made or cultural feature on Earth. A feature can have different names in one or several languages and the names may be provided, together with appropriate information on the feature, in different products like maps and gazetteers as well as respective services. Based on defintion from https://inspire.ec.europa.eu/theme/gn[EU INSPIRE].

[[geoferencing]]
== Georeferencing
Georeferencing means to associate an object with a position in physical space. Postion is most commonly represented using a coordinate reference system, which in turn can be related to a geodetic reference system such as WGS-84.

[[habitat]]
== Habitat

[[mat-samp-state]]
== Material Sample State
Represents the state of a material sample when its condition is negatively impacted. Fixed values include: destroyed, damaged, lost or decommissioned

[[mat-samp-type]]
== Material Sample Type
A Material Sample is a physical result of a sampling (or subsampling) event. In biological collections, the material sample is typically collected, and either preserved or destructively processed. A Material Sample Type is a system-defined term that prescribes the downstream expectations and logic in how derivative (or child) Material Samples are to be interpreted and digitally managed.
Fixed values include: Whole Organism, Molecular Sample, Organism Part or Mixed Organisms.

[[person]]
== Person
A definitive, canonical representation of a human in the Agent module that has been ideally disambiguated through inclusion of an externally referenced identifier.

[[preparation-fixative]]
== Preparation Fixative
Solution that was applied to or in which the material sample is preserved.
Examples: EtOH 95%, EtOH 75%, EtOH 70%, saline, glue

[[preparation-medium]]
== Preparation Medium
Additional, typically inert physical environments or objects in which or on which the organism in a material sample is stored. It does not express the state of the organism nor the fixatives used but rather the materials that allow the organism to be presented.

Examples: pinned, glass vial, plastic jar, glass jar, microscope slide, acid-free paper, sticky trap/card, Eppendorf tube

[[preparation-substrate]]
== Preparation Substrate
Material on which the organism in the material sample is presented or grows.
Examples: rock, log, agar

[[reverse-geocoding]]
== Reverse geocoding
Reverse geocoding is the process of converting a location as described by geographic coordinates (latitude, longitude) to a human-readable place name.

