[[Search]]

= Searching the Stored objects

[[Metadata]]
== Metadata

Quick exlaination of searchs

=== Search object attributes
While there are many attribues to search the fall into three groups
* Text - which can have any text in them
* List - a drop down list of limited choses
* date - a calender data and time.

The search options for Text and list are the same
* Exact match
* Partial Match
- Not Equals 
- Empty 
- Not Empty 

---

A Note on partal match.

The method to make these searches fast on large dataset results in a partial search not gareunteeing to file a longer bit of text. For example there was a archive where doing a search on "book" did not return a "book1.txt"

Work is still being done to find the optimal tradoff between speed and returns

---

* Date data type has the following comparitors 
- Equals 
- Not Equals 
- Greater Than 
- Greater Than or Equal to 
- Less Than 
- Less Than or Equal to

=== Parts of the spearch page

The search allow one to select one of the object attributes
A comprisons opperation depending on the type of the object attribute

Searches are created in the search section of the page

Two buttons exist at the right hand side of the page. These are Add Query and Add Sub Query.

The add Query button is used to create a new entery to the search. 

When a new query is added the object attributre to be searched os chosen, A comparison choice is chosen, And a value that is compared to is enerted into the field.

Addition query can be added to the search by pressing the add button

=== combinigng multiple searches

Multiple searches can be combined for more accuray. for example all samples with a date of 2019 could be found by searching for those that are 
have a creation date Greather than or Equal to Jaunary 1st 2019
And
a create date Less than or Equal to Decepmber 31st 2019

The Or search can be used for combining multiple    
