= Workbook Upload

The Workbook Upload functionality can be used to quickly add some records to DINA. It should be used to add a small number of new records but it is not a mechanism designed to perform a data migration from another source. Migration should be done at the API level since a lot of coordination, validation and checks are necessary.

== Limitations

* Usage limited to <<mat-sample, material-sample>> and its relationships
* The relationships should already exist in the system and can't be created by the same Workbook with the exception of the followings:
** <<collecting-event>> that is only linked to the new material-sample
** <<organism>>
* No records can be updated using the Workbook Upload, records can only be added

== Relationships
Relationships in Workbooks are expressed as textual representation unless a UUID (Universal Unique Identifier) is provided. The Workbook Upload will need to map the textual representation to existing concepts in the DINA system. With the exception of collecting-event, all records where the relationships are pointing must already exist before the import.

=== Text vs Concept
In a Workbook, textual representation are used to express concepts. For example, the text "Michael Jordan" could mean https://en.wikipedia.org/wiki/Michael_Jordan[Michael Jordan] or https://en.wikipedia.org/wiki/Michael_Jordan_(mycologist)[Michael Jordan] or one of https://en.wikipedia.org/wiki/Michael_Jordan_(disambiguation)[multiple people]. There is no way to automatically pick the right person without having more information. A globally unique and persistent identifier exists and can be used to clearly identified a concept. For researchers https://orcid.org/[ORCID] can be used to identify researchers without any ambiguity. DINA generates <<identifier>> for all of the data that it stores.
