name: Build and Deploy User Guide

on: [push]

permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v6
      - name: Install asciidoctor
        run: |
           sudo apt-get install -y asciidoctor
      - name: Run generate documentation for User Guide
        run: asciidoctor -a toc=left -D generated-docs asciidoc/user-guide/index.adoc
      - name: Run generate documentation for Basic Functionalities Guide
        run: asciidoctor -a toc=left -D generated-docs/concepts-glossary asciidoc/concepts-glossary/index.adoc
      - name: Run generate documentation for Developer Guide
        run: asciidoctor -a toc=left -b html5 -D generated-docs/developer asciidoc/developer-guide/index.adoc
      - name: Copy images for Developer Guide
        run: |
          mkdir generated-docs/developer/images
          mkdir generated-docs/images
          cp -r asciidoc/developer-guide/images/. generated-docs/developer/images
          cp -r asciidoc/user-guide/images/. generated-docs/images
          cp -r asciidoc/concepts-glossary/images/. generated-docs/concepts-glossary/images
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'generated-docs'
         
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

