name: Build and Deploy User Guide

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install asciidoctor
        run: |
           sudo apt-get install -y asciidoctor coderay
      - name: Run generate documentation for User Guide
        run: asciidoctor -a toc=left -D generated-docs asciidoc/user-guide/index.adoc
        
      - name: Run generate documentation for Developer Guide
        run: asciidoctor -a toc=left -D generated-docs/developer asciidoc/developer-guide/index.adoc

      - name: Deploy GitHub Pages (only on master branch)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: generated-docs
